### ISSUE TITLE
COUCH2PG_USERS_META_DOC_LIMIT Safety Check

### ISSUE THREAD

**Issue by nomulex** [medic/cht-couch2pg#99] opened 2021-07-01 07:23 UTC
We need to put a numerical safety check on [this](https://github.com/medic/cht-couch2pg/blob/master/env.js#L20) variable to guard against wrong entries.

**Comment by mrsarm** [comment] 2021-07-01 14:22
@nomulex could you specify what would be the acceptable range?

Moreover, I noticed that we didn't document the variable in the table [here](https://github.com/medic/cht-couch2pg#running-locally-with-environment-variables), a good definition with recommendations about what value to set is [here](https://github.com/medic/cht-couch2pg/blob/3e38727075c0132fad3f3e41c4a4461b202519de/inquirer.js#L65), so just a note to add that same description in the same PR in the README file.

**Comment by garethbowen** [comment] 2021-07-01 19:27
I think the main thing is to make sure it's numerical using the `safeNum` function just like the other environment variables. We could also check that it's greater than 0, but I think that's overkill.

**Comment by nomulex** [comment] 2021-07-02 07:18
+1 @garethbowen. Just making sure it's numerical.

**Comment by mrsarm** [comment] 2021-07-06 15:04
This PR https://github.com/medic/cht-couch2pg/pull/100 is addressing this ticket, that kind of duplicate https://github.com/medic/cht-couch2pg/issues/97.

**Comment by mrsarm** [comment] 2021-08-06 12:32
We forgot to triage and assign a project to this ticket before fixing it. I just assigned it to one board and moved it to ready for test because it was fixed.

Because it is a doc fix and then only add a safety check, we should only check whether setting the variable or not the startup is affected, how it behave if a wrong value is assigned, and whether at least the sync continue to happens after a successful startup.

The branch is `97-add-documentation-on-COUCH2PG_USERS_META_DOC_LIMIT`, (https://github.com/medic/cht-couch2pg/pull/100).

**Comment by meghna-khemka** [comment] 2021-09-15 21:10
Tested above issue and issue seems to be working fine 

Scenario 1:
The launching the app without passing the variable.

![image](https://user-images.githubusercontent.com/84743933/133509546-1d44b9d1-8cbe-43af-890d-55b8111af218.png)

Scenario 2:Pass with a valid numeric number
![image](https://user-images.githubusercontent.com/84743933/133509325-de09e1a8-c179-4d27-892f-964782a45a03.png)

![image](https://user-images.githubusercontent.com/84743933/133509402-4aebd742-5748-44e2-a72b-edcbe750849b.png)

Scenario 3:Pass an invalid number.
![image](https://user-images.githubusercontent.com/84743933/133509961-7729f1f9-e4cf-4337-b34b-d674f65f80ec.png)

![image](https://user-images.githubusercontent.com/84743933/133509686-d9af202b-9272-4032-85ba-8a8d17a7b9d6.png)

**Comment by mrsarm** [comment] 2021-09-16 01:26
Actually I don't think that the last test behaves as we expected , the process should fail if an invalid number is passed, otherwise it gives the impression the value passed was "accepted" and used by medic-couch2pg, but in reality it parsed as a `NaN` value, and not sure what that means when the process tries to use the value there to limit the number of docs per request.

@njogz I know we use the same trick to parse other values (the use of `safeNum`), but maybe we have to change it to prevent future errors, or I'm missing something here...

**Comment by njogz** [comment] 2021-09-16 12:59
@mrsarm it should work with a default value if the environment variable passed is invalid which is what this [code](https://github.com/medic/cht-couch2pg/pull/100/files#diff-cbf01e88a71952667baadd3a091707e87cf2e42b0c4cff1d2569af68e134e1feR20) is supposed to do. Do you mind trying to replicate what @meghna-khemka got? I see the default value when I pass an invalid number.

**Comment by mrsarm** [comment] 2021-09-16 13:47
@njogz OK maybe it's out of scope, the behavior of `safeNum` is wrong, but previous to your work.

I have created a separated ticket to fix the issue later, and with low priority: https://github.com/medic/cht-couch2pg/issues/107

So for me the PR is OK, and because was approved in AT, going to merge.

**Closed** 2021-09-16 13:48 UTC
Labels: enhancement, Priority: 3 - Low

**Comment by meghna-khemka** [comment] 2021-09-16 16:03
@mrsarm : I think I had some Git rebase issues which lead me to believe that it showing up NaN whereas incase I pass a arbritary string in this variable.Upon testing again I can confirm that if I pass a string it is picking default value of 50 instead of NaN .I believe this is not expected? Can we get this fixed...


I think change required would be 
couchdbUsersMetaDocLimit: safeNum(process.env.COUCH2PG_USERS_META_DOC_LIMIT || 50)


![image](https://user-images.githubusercontent.com/84743933/133645765-c39734de-33e8-4373-9586-b3a46586563f.png)

**Comment by mrsarm** [comment] 2021-09-16 16:13
@meghna-khemka thanks for the new report. Anyway, this is not new, because the `safeNum` function is used in most of the numeric env variables. I have created another issue to keep track of the malfunctioning of the function: https://github.com/medic/cht-couch2pg/issues/107. Could you add your findings there please?

Anyway, returning the default value instead of a `NaN` makes the error less severe, because it's hard to know how a `NaN` may be interpreted by the different parts of the app, while default values we know are safe, but still this is a bug.
