### ISSUE TITLE
Make sure sample docker_compose works with a remote installation of CHT-Core

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-couch2pg#112] opened 2022-02-15 13:39 UTC
This came in through the forum: https://forum.communityhealthtoolkit.org/t/read-only-replica-of-couchdb-docs-into-postgres-for-data-visualization/1710/6

I found a few problems with our sample from the readme and some of the docker setup: 

1. It adds a CouchDb container (presumably to use as a source) when cht-couch2pg is supposed to get data out of a CHT instance. Incidentally, the container throws a lot of errors, obfuscating what is actually going on. 
My proposed solution is to remove the CouchDb container entirely and have the sample connect to a CHT instance CouchDb

2. If I set my `COUCHDB_URL` env to be a remote CHT instance (for example: `https://admin:pass@192-168-1-253.my.local-ip.co/medic`), the entry script ends up in an infinite retry loop because it expects a 200 response code. API responds with a 302 on the non-slash ending URL. This can be worked around with setting the URL to `https://admin:pass@192-168-1-253.my.local-ip.co/medic/`, but this seems like kind of a hack. 
My proposed solution is to not [grep specifically for 200](https://github.com/medic/cht-couch2pg/blob/main/couch2pg-entrypoint.sh#L36), but for a generic success status or change the curl command to follow redirects. 

3. After doing the above, I ran into SSL issues with the `my.local-ip.co` cert. 
Specifically: 
```
cht-couch2pg  | https://admin:pass@192-168-1-253.my.local-ip.co/medic
cht-couch2pg  | Set postgres URL to postgres://cht_couch2pg:couch2pg_password@cht-postgres:5432/cht
cht-couch2pg  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
cht-couch2pg  |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
cht-couch2pg  | curl: (60) SSL certificate problem: certificate has expired
cht-couch2pg  | More details here: https://curl.haxx.se/docs/sslcerts.html
cht-couch2pg  | 
cht-couch2pg  | curl performs SSL certificate verification by default, using a "bundle"
cht-couch2pg  |  of Certificate Authority (CA) public keys (CA certs). If the default
cht-couch2pg  |  bundle file isn't adequate, you can specify an alternate file
cht-couch2pg  |  using the --cacert option.
cht-couch2pg  | If this HTTPS server uses a certificate signed by a CA represented in
cht-couch2pg  |  the bundle, the certificate verification probably failed due to a
cht-couch2pg  |  problem with the certificate (it might be expired, or the name might
cht-couch2pg  |  not match the domain name in the URL).
cht-couch2pg  | If you'd like to turn off curl's verification of the certificate, use
cht-couch2pg  |  the -k (or --insecure) option.
```
I worked around this with the `--insecure` parameter, but it's a pain for users to hit this and not understand what is happening. 
I saw the error because I added an additional curl before the `until`, otherwise the user would just see the `Waiting for cht couchdb` message over and over. 

4. After fixing the above points, I started seeing the [`check_if_postgres_is_ready`](https://github.com/medic/cht-couch2pg/blob/main/couch2pg-entrypoint.sh#L19) function stay in a retry loop, even though the container reported it was ready to accept connections: 
```
cht-postgres  | 
cht-postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
cht-postgres  | 
cht-postgres  | 2022-02-15 13:14:22.728 UTC [1] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
cht-postgres  | 2022-02-15 13:14:22.728 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
cht-postgres  | 2022-02-15 13:14:22.728 UTC [1] LOG:  listening on IPv6 address "::", port 5432
cht-postgres  | 2022-02-15 13:14:22.734 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
cht-postgres  | 2022-02-15 13:14:22.740 UTC [26] LOG:  database system was shut down at 2022-02-15 13:13:43 UTC
cht-postgres  | 2022-02-15 13:14:22.746 UTC [1] LOG:  database system is ready to accept connections
cht-couch2pg  | Starting couch2pg process
cht-couch2pg  | Set postgres URL to postgres://cht_couch2pg:couch2pg_password@cht-postgres:5432/cht
cht-couch2pg  | http://admin:pass@192.168.1.253:6500/medic
cht-couch2pg  | couchdb  is ready
cht-couch2pg  | Waiting for PostgreSQL...
cht-couch2pg  | Waiting for PostgreSQL...
cht-couch2pg  | Waiting for PostgreSQL...
```
Running the command outside the until, without the `quiet` param, yields:
```
cht-couch2pg  | Starting couch2pg process
cht-couch2pg  | Set postgres URL to postgres://cht_couch2pg:couch2pg_password@cht-postgres:5432/cht
cht-couch2pg  | http://admin:pass@192.168.1.253:6500/medic
cht-couch2pg  | couchdb  is ready
cht-couch2pg  | cht-postgres:5432 - no attempt
cht-couch2pg exited with code 3
```

According to the documentation, `no attempt` seems to indicate invalid parameters (https://www.postgresql.org/docs/9.3/app-pg-isready.html). Using `--d` is invalid, but changing to `-d` doesn't fix the issue. 
This is because the `cht-couch2pg` container isn't part of the network. 
OFC, proposed solution is to add the container to `cht-net`.

**Comment by dianabarsan** [comment] 2022-02-15 15:28
>While it is separated by an empty line, the cht-couch2pg [service was on the cht-net network](https://github.com/medic/cht-couch2pg/blob/main/docker-compose.test.yml#L43).

@mrjones-plip in the docker-compose.test.yml it was, but not in the readme: https://github.com/medic/cht-couch2pg/blame/main/README.md#L133 , which is where some users might end up with taking samples.

**Comment by mrjones-plip** [comment] 2022-02-16 20:42
@dianabarsan  - you're so right!  Sorry I missed that. I'm a huge fan of having only one copy of files so it's easier to keep them updated when making changes - less things to keep in sync.  

Oh no! Looking further, I see that the readme version has `COUCHDB_URL` in the `cht-couch2pg` service which the file based one was missing too. Double oh no!  It also uses a different image that the docker file (build from `Dockerfile` vs published `medicmobile/cht-couch2pg:v3.2.0-node-10`)!?  I think this explains why my experience was so very different than yours.

CC @njogz  who I know was looking into this too.

**Comment by mrjones-plip** [comment] 2022-02-22 23:41
I see that the same docker compose file is on [docker hub](https://hub.docker.com/r/medicmobile/cht-couch2pg) - we should be sure to fix it there too. A better solution is likely to point to GH as a canonical docker file so we only have to keep one up to date.

**Comment by garethbowen** [comment] 2022-02-23 23:16
@mrjones-plip I think it's probably worth tidying your PR up and getting it merged as it looks to be in the right direction. There's a CI issue to solve as well but hopefully that's not too challenging. It doesn't have to be a high priority but it'd be good to make this usable until a replacement is ready.

**Comment by mrjones-plip** [comment] 2022-02-23 23:41
OK - awesome! Thanks @garethbowen  for the nudge in the right direction.  

Given I started off by using the "test" compose file (the wrong one), I think the right plan is then something like this:
* label existing `docker-compose.test.yml` as the one for CI and what ever else SRE does with with - not breaking the flow that uses this
* create a new compose file based off [readme](https://github.com/medic/cht-couch2pg#10-postgres_password)
* ensure new compose file does not have couchdb service - BYOCouchDB ;)
* ensure there is only one - so remove inline compose file from readme and from [docker hub](https://hub.docker.com/r/medicmobile/cht-couch2pg) - replace with something like `curl https://github-url-here -o docker-compose.yml`
* Update compose file to have correct env vars, networks and override-able values
* make sure it all works with external couch instances

cc @dianabarsan @njogz and @eljhkrr  for anything I'm missing!

**Comment by mrjones-plip** [comment] 2022-03-10 22:54
@eljhkrr - We've merged everything to `main`, all that's left for us to do is publish a new image on docker hub.  Are you free to do some user acceptance testing before we publish?  

These are the steps:
1. Make sure your clone of this repo is up to date and on `main`: `git checkout main&&git fetch&&git pull origin main`
2. Rebuild the image: `docker build -t medicmobile/cht-couch2pg:master-node-10 .`
3. Make sure you CouchDB instance is up and running.  Let's use `192-168-68-26.my.local-ip.co:8443/` as an example
4. Run the compose command with your freshly built image pointing to your CouchDB instance with a one-liner: `COUCHDB_URL=https://medic:password@192-168-68-26.my.local-ip.co:8442/medic docker-compose up`

Let me know how it goes or if you're not free to test.  Much thanks!

**Comment by eljhkrr** [comment] 2022-03-11 07:18
Ran through all the steps and encountered an authentication failure
```
postgres_1      | 2022-03-11 06:41:20.330 UTC [34] DETAIL:  Role "cht_couch2pg" does not exist.
postgres_1      | 	Connection matched pg_hba.conf line 99: "host all all all md5"
cht-couch2pg_1  | [2022-03-11T06:41:20.332Z ERROR]:  An unrecoverable error occurred
cht-couch2pg_1  | [2022-03-11T06:41:20.332Z ERROR]:  { error: password authentication failed for user "cht_couch2pg"
cht-couch2pg_1  |     at Connection.parseE (/app/node_modules/couch2pg/node_modules/postgrator/node_modules/pg/lib/connection.js:539:11)
cht-couch2pg_1  |     at Connection.parseMessage (/app/node_modules/couch2pg/node_modules/postgrator/node_modules/pg/lib/connection.js:366:17)
cht-couch2pg_1  |     at Socket.<anonymous> (/app/node_modules/couch2pg/node_modules/postgrator/node_modules/pg/lib/connection.js:105:22)
cht-couch2pg_1  |     at Socket.emit (events.js:198:13)
cht-couch2pg_1  |     at addChunk (_stream_readable.js:288:12)
cht-couch2pg_1  |     at readableAddChunk (_stream_readable.js:269:11)
cht-couch2pg_1  |     at Socket.Readable.push (_stream_readable.js:224:10)
cht-couch2pg_1  |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
cht-couch2pg_1  |   name: 'error',
cht-couch2pg_1  |   length: 108,
cht-couch2pg_1  |   severity: 'FATAL',
cht-couch2pg_1  |   code: '28P01',
cht-couch2pg_1  |   detail: undefined,
cht-couch2pg_1  |   hint: undefined,
cht-couch2pg_1  |   position: undefined,
cht-couch2pg_1  |   internalPosition: undefined,
cht-couch2pg_1  |   internalQuery: undefined,
cht-couch2pg_1  |   where: undefined,
cht-couch2pg_1  |   schema: undefined,
cht-couch2pg_1  |   table: undefined,
cht-couch2pg_1  |   column: undefined,
cht-couch2pg_1  |   dataType: undefined,
cht-couch2pg_1  |   constraint: undefined,
cht-couch2pg_1  |   file: 'auth.c',
cht-couch2pg_1  |   line: '334',
cht-couch2pg_1  |   routine: 'auth_failed',
cht-couch2pg_1  |   helpfulDescription: 'Prep() table CHECK query Failed' }
```

**Comment by mrjones-plip** [comment] 2022-03-11 14:53
Awesome - thanks for testing! 

I suspect that there was one or two containers around from last time that have different credentials? I see `error: password authentication failed for user "cht_couch2pg"` which is why I think that.

If you have no important data in them, can you please stop all your couch2pg related containers, delete them and delete their volumes, and try again?  Important here will be to delete the data volume for postgres.  Here's what this deleting looked like for me:

```
$ docker ps -a --filter name=couch --format '{{.Names}}'
cht-couch2pg_cht-couch2pg_1
cht-couch2pg_postgres_1
medic-couchdb
cht-couch2pg_couch_1

$ docker rm -f cht-couch2pg_couch_1 cht-couch2pg_postgres_1 cht-couch2pg_cht-couch2pg_1
cht-couch2pg_couch_1
cht-couch2pg_postgres_1
cht-couch2pg_cht-couch2pg_1

$ docker volume ls
DRIVER    VOLUME NAME
local     0cfb914ab18a7904181b9227b86afe10f3cd44dcc8bccf42236d00cd6fc39f32
local     bb5f10796f72c240fa825500b05b8b03559c914a672e2dba076e7e80fd869108
local     cht-postgres-data
local     docker_debug_medic-data

$ docker volume rm cht-postgres-data 
cht-postgres-data
```

In prior versions the `COUCH2PG_USER` wasn't actually used - we used the built in `POSTGRES_USER` which isn't how it was intended.  Further, I went out of my way to have the [values be more easy to know which is which](https://github.com/medic/cht-couch2pg/blob/main/sample.env). I think you had a both a `postgres-data` volume and possibly a container with old credentials

Let me know the results!

**Comment by eljhkrr** [comment] 2022-03-11 16:39
You're right, after cleaning out the older containers and starting afresh, I'm seeing docs being pulled into postgres

**Comment by mrjones-plip** [comment] 2022-03-11 17:24
That's wonderful news! Thanks for the testing.

I'll work to publish out a new image in #113!

**Closed** 2022-03-11 17:24 UTC
